version: '2.3'
services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/Forgos-ynov/m1-deploiement-continue
      RUNNER_NAME: runner-github
      RUNNER_TOKEN: AVRGC5DTZSC5ZE7QRQW5LRLGOFGY2
      LABELS: linux,x64,gpu
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
