name: runner-gitHub
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  clone-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Wait for the services to be ready
        run: sleep 15

      - name: Make curl request to nginx
        run: |
          docker compose exec web curl -s http://localhost

      - name: Docker compose down
        run: docker compose down
